"""extending db.text field length

Revision ID: 22beab22e158
Revises: f95781b8afc7
Create Date: 2018-11-21 15:36:05.285747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22beab22e158'
down_revision = 'f95781b8afc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=mysql.TEXT(),
               type_=sa.Text(length=100000),
               existing_nullable=True)
    op.alter_column('post', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.Text(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'description',
               existing_type=sa.Text(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('post', 'body',
               existing_type=sa.Text(length=100000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
