"""empty message

Revision ID: f95781b8afc7
Revises: 9423b06079f2
Create Date: 2018-11-13 22:59:52.853635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f95781b8afc7'
down_revision = '9423b06079f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=mysql.TEXT(),
               type_=sa.Text(length=10000),
               existing_nullable=True)
    op.alter_column('post', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.Text(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'description',
               existing_type=sa.Text(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('post', 'body',
               existing_type=sa.Text(length=10000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
